openapi: 3.0.0
info:
  title: Swagger Example API
  description: Here goes description
  version: 0.1.9

servers:
  - url: http://localhost:8000/api
    description: local server
  - url: http://producation.app/api
    description: production server

components:
  securitySchemes:
    bearerAuth:           
      type: http
      scheme: bearer
      bearerFormat: JWT 


paths:
  /swagger-login:
    post:
      summary: log in and get access token directly in response
      responses:
        '200': 
          description: access token
          content:
            application/json:
              schema: 
                type: object
                properties: 
                  access_token:
                    type: string
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string  

  /me:
    get:
      summary: retreives information about authenticated user
      security:
      - bearerAuth: []
      responses:
        '200': 
          description: authenticated user
          content:
            application/json:
              schema: 
                type: object
                properties: 
                  user:
                    type: object
                    properties:  
                      id:
                        type: integer
                      email:  
                        type: string
                      created_at:
                        type: string
                  message:
                    type: string      